language: python
python:
- '3.6'
install:
- pip install pycrypto
- pip install 'molecule[gce]'
script:
- molecule create
- molecule converge
- molecule verify
gitafter_script:
- molecule destroy
before_install:
- openssl aes-256-cbc -K $encrypted_dbbd4c0ab462_key -iv $encrypted_dbbd4c0ab462_iv -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- mv google_compute_engine /home/travis/.ssh/
- chmod 0600 /home/travis/.ssh/google_compute_engine
- ln -s $(pwd) $(dirname `pwd`)/$ROLE_NAME
- export ANSIBLE_ROLES_PATH="$(dirname `pwd`)/$ROLE_NAME"
notifications:
  slack:
    rooms:
      secure: XOg5Vk2Is2bT4Sq58TYXbuv3LJSCB+cmyQHss8O2lhh2ryG39mZj761ZiCJwKeAHh/ibsQkCmN/QqJZ+ggnVR7BJLfUJPX4CTpTNRZywHUeo+adBTmp/QplDg/zgTKzQkwfoA7uMUEapWln1WIpACtrUX3D+Fa4AtswarZMuBnjTyPYqFiAuLZ8RuaiYSc5pERZhFm7tm7cfUmZSMpA/K268Qr/EttTpinkBZBY1qGb+F6+Ps8SoQ4zsZf7M+lPs93byX5wUqth6l3YPTBc89pFc3YOgS6JPCQJ+IerhODm0r3gqNuMF6Mu2W7n80t6xUYhD9itL0OL1HEGrK49JoYxjTHQ0o6AfurO/jXnGmkWRXP9TCTAqL+q6tQHJvwFuTAZWXAPfelxvQfhAWKcG/1ke5x3X98wCtNhqS+W99S69R5UShzXrmX2MOg5XTQaLfKT280ipgtWUSj0VK+Zgy05FqtuKFNgcjm3Z/PolCxMM1TzkPFMbpxm0fecmqrZTlwQpm3j6cbzppr+FDdLmaenzj7RjtuqCJPX0e64lo3PKf4gGkUM1YllCOhDniCOiR1Jad0NWB1/hUB/MWindjwO4enNBkS/+YxGQQTNQIsXM5UPnUTLU7ACIz9SDcm8DmK+C+t688XghmzoIj0tOLJb/60I6qdODI2CbcyUt+PU=
env:
  global:
  - ROLE_NAME: db
  - secure: TsJ9bBfUx1cMIMOKY0v65Hv3nCXRV9E3N0CDYjHiMZQ/3+e7KZqkSqFOfJeFROPRJAG95pltej1JuCcADH9F1yJkzVkjsTHoT6TexHRSSwdpjVd6Gk4Y6gv7awPxRF5EJa7vY80tC0fMmzapvp67vxYO6Ab42T5wK3zO9tlx2bHVyBX716RrYEgqcUjzcVuNieJjxsVEE+ACRcoSLe6LKD+MNS5+5uAFQ50azyO1GbFTXyy1JPtVQtkyIb0Na9LUBtaohkL2zGHdszeTeO+gYEdwIK+/qcOoMjZY1eL8j3yaQG7oYyeHp/uwv/hCGnfQaU/UlqYVcqZyWDKo1RRxbaQH6NquAxAlStA3UZtAsVlTtU9UudixoZYO7r/ebYQ/wzeHuz0Gp0DNu72dI2ekrDz0zhy9DiBk/B6jkVbqN9KVpwFRUO6WVQAAXdIblWfpbGMN8vcKp6YbYq2cIZXF08EuuvUu91rU8vgsNMkcvhhpPbZx3Se8zal3hcHyqMjKHOmEfoGviBPdag3qmnHySqLPPb9CCGKSTxumvsNJaOh7a2lw1kDf5tu/h1QdIz7ttXneSef2VR5bqlV2qKg1NVXuJaZ5OU6ApMEwtET8DpiSI/4DLrSc7kROcGjT7QISfb+co/UybggQoLHiwBrS7DJkqD8L21W3ubP/eA/7HEg=
  - secure: NgDH/dULfBMh/duuuPvXA1niqDnnVEtYnd3jtv4mUcSteWvpbfJ2aMYqXf4uvmA7flqSnKSBAJ8lKXCjbQ+5HwvQpdHgMtdA/wDjdyVgvNr3H6FiQ9NWvi9W1Vz687yzQxymtVUcIcqjtihLmHpHBmAUJv4bmR0NivqnnDKVTI6i6tfVO+sX1VbmGm4avI1eGjy+5WvmAqNmbi3iK7o4B/oaNW2GA5olA0a53ktl8pOyxhKy1e/1oSntHxI+f/O1u2EjDM/FtxuE4RSd+I8oEGX6POJOfFnY/FNZNiyA2zzwMc7OYrYYArzAWsdZtlAK6hzPwb/ECMDKTTYA4IMoTzQe4R/pCVV1cMsb25lHwLV2Hlf/9mad2X/zE4kHg/4gVV90BYNTqI6ziHy/ACNb+VU2A+7xx+vHDI1D5yo3W6PPLrei35fGNNfplcGcVUB7AyHGDltA62jf4pNSfyjbTc82Mh0ntQ2YEeHQuirXRjf8IKe6EDhuCGfYzNX1HGi0hZ3jqWgX9xy901R/0adTtelmxd4YNNtfgkHFPLBWzu0SgDE9bcWxGziLC95diM5bR2N5XyJh3RICHjPK4uS+PfuyRy27tLB5sAYhj6QdKTtob2mkMA6g3O0Ynldzv8RxmjK6S5uTG8DVifODe8u7KB8kaSCCzvXWc9qePpsdesk=
  - secure: WxRv9sHlbDmJng42KkBmjkMnDfyRvTFNOhIaB5+GjGtvLXcvlvIfqSbYcZTkI2LS/JcUVdoa82Q/8OTvGfpYCylAVrsf//SvqE9OSGssjuXkHEPhIj+pSg8QuYlLmauU7pmvdNsPApguUL5bL7UrnyBvQEoCf1QsCcehFHOXVcdJ6KyrWLEg4jfIQhtBUywzWMBEFsQnJF2Xi2vZDndMM57L5uNBakMnx9bbPlTnMrGH0oUSxT4udRLyO/2p+0v1fAIVRSmJRMaeqBhI6o5nnIkuS93PmD0FoqBHCpQNkL5ZM+0GxCw/XadfwHCxmftGMTqobAv6FO75xAyLsDrGi1g5NtwrCw4rnYbxiUlr+tXqA893GPRK6hperKHTsXBvqDatR7n9/mgvxt5YOCcni68/PlBW1XGJM6aT3caYutMTUT8u8p21hn+OEWvcLP6GF62TP6yGE2VYyIr0M7sJOEsuBGMe3r5s3jYBnXaRLmMPkD0Qs+Y0BWUFcTBkWXWLa+H4uLSsiJc+4V/o1cnFmmOnq6JbEdMIXQ27pjg/tRbNF0NPHMB8EBTuk195vH3N9Vjc/EEph+JuN1aww4oaX2cnzzHxLQpIM+ijo0GePPnBiAVA2gq86IM5s6jo1nQ0k8uLakNs7VasJHoTc/r5KdSprjBv368URP6YKdax9TE=
